/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/areYou` | `/areYou`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pros` | `/pros`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cons` | `/cons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/catLovers` | `/Categories/catLovers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/catParents` | `/Categories/catParents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/newCatParents` | `/Categories/newCatParents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/thinkingOfAdopting` | `/Categories/thinkingOfAdopting`; params?: Router.UnknownInputParams; } | { pathname: `/routes/startingStack`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/areYou` | `/areYou`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pros` | `/pros`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cons` | `/cons`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Categories/catLovers` | `/Categories/catLovers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Categories/catParents` | `/Categories/catParents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Categories/newCatParents` | `/Categories/newCatParents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Categories/thinkingOfAdopting` | `/Categories/thinkingOfAdopting`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/startingStack`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/areYou${`?${string}` | `#${string}` | ''}` | `/areYou${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pros${`?${string}` | `#${string}` | ''}` | `/pros${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cons${`?${string}` | `#${string}` | ''}` | `/cons${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Categories/catLovers${`?${string}` | `#${string}` | ''}` | `/Categories/catLovers${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Categories/catParents${`?${string}` | `#${string}` | ''}` | `/Categories/catParents${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Categories/newCatParents${`?${string}` | `#${string}` | ''}` | `/Categories/newCatParents${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Categories/thinkingOfAdopting${`?${string}` | `#${string}` | ''}` | `/Categories/thinkingOfAdopting${`?${string}` | `#${string}` | ''}` | `/routes/startingStack${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/areYou` | `/areYou`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pros` | `/pros`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cons` | `/cons`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/catLovers` | `/Categories/catLovers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/catParents` | `/Categories/catParents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/newCatParents` | `/Categories/newCatParents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Categories/thinkingOfAdopting` | `/Categories/thinkingOfAdopting`; params?: Router.UnknownInputParams; } | { pathname: `/routes/startingStack`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
